#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

killall stats_provider
# Update with path to stats_provider
$CONFIG_DIR/sketchybar-system-stats/target/release/stats_provider --cpu usage --memory ram_usage swp_usage &

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="Monaspace Argon Semibold" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
ICON_FONT="SF Pro"
PADDINGS=3 # All paddings use this value (icon, label, background)

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

# aerospace setting
AEROSPACE_FOCUSED_MONITOR_NO=$(aerospace list-workspaces --focused)
AEROSPACE_LIST_OF_WINDOWS_IN_FOCUSED_MONITOR=$(aerospace list-windows --workspace $AEROSPACE_FOCUSED_MONITOR_NO | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

# got the files from here: https://github.com/forteleaf/sketkchybar-with-aerospace/tree/main

# Setting up the general bar appearance of the bar
bar=(
  height=34
  color=$BAR_COLOR
  border_width=2
  border_color=$BAR_BORDER_COLOR
  shadow=off
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  y_offset=-1
  margin=-2
  topmost=window
  color=0x00000000
  border_color=0x00000000
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="Monaspace Argon Semibold:Semibold:15.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINS
  icon.padding_right=$PADDINGS
  label.font="Monaspace Argon Semibold:Semibold:15.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  label.shadow.drawing=off
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=off
  scroll_texts=on

)

sketchybar --default "${defaults[@]}"


# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

source "$ITEM_DIR/spotify.sh"


# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/power.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/memory.sh"
source "$ITEM_DIR/disk.sh"

#sketchybar --add item cpu_usage right \
#	   --set cpu_usage script="sketchybar --set cpu_usage label=\$CPU_USAGE \(\$CPU_TEMP\)" \
#		 background.color=$BACKGROUND_1 \
#		 background.border_color=$BACKGROUND_2 \
#		 padding_left=2 \
#		 padding_right=2 \
#		 label.padding_right=10 \
#		 icon.padding_left=8 \
#		 icon="􀫥" \
#	    --subscribe cpu_usage system_stats
#
#sketchybar --add item ram_usage right \
#           --set ram_usage script="sketchybar --set ram_usage label=\$RAM_USAGE \(\$SWP_USAGE\)" \
#		 background.color=$BACKGROUND_1 \
#		 background.border_color=$BACKGROUND_2 \
#		 padding_left=2 \
#		 padding_right=2 \
#		 label.padding_right=10 \
#		 icon.padding_left=8 \
#		 icon="􀫦"\
#           --subscribe ram_usage system_stats




sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
